#include "t2sort_i.h"
#include "gentype.c"

#include "aio_posix.c"
#include "t2sort_debug.c"
#include "t2sort_open.c"
#include "t2sort_map_sort.c"
#include "t2sort_write.c"
#include "t2sort_align.c"
#include "t2sort_sort.c"
#include "t2sort_read.c"
#include "t2sort_close.c"
